package com.halalcms.applicationservice.model;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    UNDER_REVIEW,
    AGREEMENT_PENDING,
    AGREEMENT_REVIEW,
    AGREEMENT_APPROVED_BY_HCB,
    PENDING_PAYMENT,
    PAYMENT_REVIEW,
    AUDIT_SCHEDULED,
    DOCUMENT_SUBMISSION,
    AUDIT_IN_PROGRESS,
    AUDIT_COMPLETED,
    NC_CLEARANCE,
    DECISION_MAKING,
    CERTIFICATION_REVIEW,
    CERTIFIED,
    REJECTED,
    SUSPENDED,
    EXPIRED
}
