name: Smart Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      # fetch-depth: 0 ensures full git history is available for accurate diffing
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Detect Changes
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'halal-cms-backend/**'
            frontend:
              - 'halal-cms-frontend/**'

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Make script executable
        run: chmod +x halal-cms-backend/compile.sh

      - name: Build & Push Backend
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          cd halal-cms-backend
          ./compile.sh

      - name: Deploy Backend on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DO_API_TOKEN
          script: |
            echo "$DO_API_TOKEN" | docker login registry.digitalocean.com -u doctl --password-stdin
            cd /home/dev-ahdaah/qhx
            chmod +x service.sh
            ./service.sh
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Make script executable
        run: chmod +x halal-cms-frontend/push-docker.sh

      - name: Build & Push Frontend
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          cd halal-cms-frontend
          ./push-docker.sh

      - name: Deploy Frontend on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DO_API_TOKEN
          script: |
            echo "$DO_API_TOKEN" | docker login registry.digitalocean.com -u doctl --password-stdin
            cd /home/dev-ahdaah/qhx
            chmod +x qhx-frontend.sh
            ./qhx-frontend.sh
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
